### ISSUE TITLE
Expresiones booleanas

### ISSUE THREAD

**Issue by Eddi3mendoz** [SistemasTecTlaxiaco/actividad-10-expresiones-boolenas-equipo-edwin#1]
[Ejercicios de expresiones booleanas.pdf](https://github.com/user-attachments/files/18044579/Ejercicios.de.expresiones.booleanas.pdf)

**Comment by Ivan-PerezZ** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
